export const FINANCIAL_LIST_REQUEST = "FINANCIAL_LIST_REQUEST";
export const FINANCIAL_LIST_SUCCESS = "FINANCIAL_LIST_SUCCESS";
export const FINANCIAL_LIST_FAIL = "FINANCIAL_LIST_FAIL";

export const FINANCIAL_UPDATE_REQUEST = "FINANCIAL_UPDATE_REQUEST";
export const FINANCIAL_UPDATE_SUCCESS = "FINANCIAL_UPDATE_SUCCESS";
export const FINANCIAL_UPDATE_FAIL = "FINANCIAL_UPDATE_FAIL";
