export const FORUMPOST_LIST_REQUEST = "FORUMPOST_LIST_REQUEST";
export const FORUMPOST_LIST_SUCCESS = "FORUMPOST_LIST_SUCCESS";
export const FORUMPOST_LIST_FAIL = "FORUMPOST_LIST_FAIL";

export const FORUMPOST_DETAILS_REQUEST = "FORUMPOST_DETAILS_REQUEST";
export const FORUMPOST_DETAILS_SUCCESS = "FORUMPOST_DETAILS_SUCCESS";
export const FORUMPOST_DETAILS_FAIL = "FORUMPOST_DETAILS_FAIL";

export const FORUMPOST_CREATE_REQUEST = "FORUMPOST_CREATE_REQUEST";
export const FORUMPOST_CREATE_SUCCESS = "FORUMPOST_CREATE_SUCCESS";
export const FORUMPOST_CREATE_FAIL = "FORUMPOST_CREATE_FAIL";

export const FORUMPOST_UPDATE_REQUEST = "FORUMPOST_UPDATE_REQUEST";
export const FORUMPOST_UPDATE_SUCCESS = "FORUMPOST_UPDATE_SUCCESS";
export const FORUMPOST_UPDATE_FAIL = "FORUMPOST_UPDATE_FAIL";

export const FORUMPOST_DELETE_REQUEST = "FORUMPOST_DELETE_REQUEST";
export const FORUMPOST_DELETE_SUCCESS = "FORUMPOST_DELETE_SUCCESS";
export const FORUMPOST_DELETE_FAIL = "FORUMPOST_DELETE_FAIL";

export const FORUMCOMMENT_CREATE_REQUEST = "FORUMCOMMENT_CREATE_REQUEST";
export const FORUMCOMMENT_CREATE_SUCCESS = "FORUMCOMMENT_CREATE_SUCCESS";
export const FORUMCOMMENT_CREATE_FAIL = "FORUMCOMMENT_CREATE_FAIL";

export const FORUMCOMMENT_UPDATE_REQUEST = "FORUMCOMMENT_UPDATE_REQUEST";
export const FORUMCOMMENT_UPDATE_SUCCESS = "FORUMCOMMENT_UPDATE_SUCCESS";
export const FORUMCOMMENT_UPDATE_FAIL = "FORUMCOMMENT_UPDATE_FAIL";

export const FORUMCOMMENT_DELETE_REQUEST = "FORUMCOMMENT_DELETE_REQUEST";
export const FORUMCOMMENT_DELETE_SUCCESS = "FORUMCOMMENT_DELETE_SUCCESS";
export const FORUMCOMMENT_DELETE_FAIL = "FORUMCOMMENT_DELETE_FAIL";
