export const MENUITEM_LIST_REQUEST = "MENUITEM_LIST_REQUEST";
export const MENUITEM_LIST_SUCCESS = "MENUITEM_LIST_SUCCESS";
export const MENUITEM_LIST_FAIL = "MENUITEM_LIST_FAIL";

export const MENUITEM_CREATE_REQUEST = "MENUITEM_CREATE_REQUEST";
export const MENUITEM_CREATE_SUCCESS = "MENUITEM_CREATE_SUCCESS";
export const MENUITEM_CREATE_FAIL = "MENUITEM_CREATE_FAIL";

export const MENUITEM_UPDATE_REQUEST = "MENUITEM_UPDATE_REQUEST";
export const MENUITEM_UPDATE_SUCCESS = "MENUITEM_UPDATE_SUCCESS";
export const MENUITEM_UPDATE_FAIL = "MENUITEM_UPDATE_FAIL";

export const MENUITEM_DELETE_REQUEST = "MENUITEM_DELETE_REQUEST";
export const MENUITEM_DELETE_SUCCESS = "MENUITEM_DELETE_SUCCESS";
export const MENUITEM_DELETE_FAIL = "MENUITEM_DELETE_FAIL";

export const MENUINGREDIENT_UPDATE_REQUEST = "MENUINGREDIENT_UPDATE_REQUEST";
export const MENUINGREDIENT_UPDATE_SUCCESS = "MENUINGREDIENT_UPDATE_SUCCESS";
export const MENUINGREDIENT_UPDATE_FAIL = "MENUINGREDIENT_UPDATE_FAIL";
