# Generated by Django 4.2.1 on 2023-06-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_userprofile_isadmin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="numReviews",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
    ]
