# Generated by Django 4.2.1 on 2023-06-14 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_ingredient_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
