# Generated by Django 4.2.1 on 2023-06-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_ingredient_unique_together"),
        ("base", "0005_alter_supplier_user"),
    ]

    operations = []
