# Generated by Django 4.2.1 on 2023-06-17 06:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_remove_menuitem_ingredients_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuingredient',
            unique_together={('menuItem', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('user', 'name')},
        ),
    ]
