# Generated by Django 4.2.1 on 2023-06-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_merge_20230619_0815"),
        ("base", "0008_alter_menuingredient_ingredient"),
    ]

    operations = []
