# Generated by Django 4.2.1 on 2023-06-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_20230621_1324'),
        ('base', '0009_merge_20230621_1821'),
    ]

    operations = [
    ]
