# Generated by Django 4.2.1 on 2023-07-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_remove_financial_profit_alter_financial_admincost"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expirationDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
