# Generated by Django 4.2.1 on 2023-07-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='noticePeriod',
            field=models.IntegerField(default=7),
        ),
    ]
