# Generated by Django 4.2.1 on 2023-07-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_userprofile_noticeperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='noticePeriod',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
