# Generated by Django 4.2.1 on 2023-07-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_userprofile_noticeperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calibratedMin',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='MenuItemSold',
            fields=[
                ('date', models.DateField(blank=True, null=True)),
                ('currentTotalSold', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.menuitem')),
            ],
            options={
                'unique_together': {('menuItem', 'date')},
            },
        ),
    ]
