# Generated by Django 4.2.1 on 2023-07-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_orderitem_expirationdate_orderitem_user'),
        ('base', '0016_ingredient_calibratedmin_menuitemsold'),
    ]

    operations = [
    ]
