# Generated by Django 4.2.1 on 2023-07-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_orderitem_unit_product_unit"),
        ("base", "0019_alter_forumcomment_user_alter_forumpost_user"),
    ]

    operations = []
