# Generated by Django 4.2.1 on 2023-07-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_merge_20230719_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="forumcomment",
            name="message",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="message",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
