# Generated by Django 4.2.1 on 2023-07-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_merge_20230719_1343'),
        ('base', '0021_orderitem_category_alter_forumcomment_message_and_more'),
    ]

    operations = [
    ]
